Use nonprofit currency symbol on donation queries
houdiniproject/houdini pull request #1323
Opened 2022-08-17 00:59 UTC by murilogds

## Description
Uses the nonprofit currency symbol to display the amount of money on donation queries

Closes #1235
Co-authored-by: Giulia Lobo <giulialobo89@gmail.com>

## Motivation to implement it
The amount of money was being displayed based on the currency configured on postgres by using postgres type cast to money:

```ruby
 Qexpr.new.select([
        'donations.created_at',
        '(payments.gross_amount/100.00)::money::text AS amount',
        'COUNT(recurring_donations.id) > 0 AS recurring',
        "STRING_AGG(campaign_gift_options.name, ',') AS campaign_gift_names"
      ]...
```

Because of this, the `rails spec` command ended up failing in systems with different currency from USD, the right behavior in this cases is to use the nonprofit currency symbol instead of postgres type cast.

## Solution summary
Instead of using postgres type cast, we decided to use the `print_currency` existing function from ApplicationHelper, for that we used map based on the query results to change the amount to the currency string displayed.

```ruby
result = QexprQueryChunker.get_chunk_of_query(offset, limit, skip_header) do
      full_search_expr(npo_id, query).select(
        'recurring_donations.created_at',
        'recurring_donations.amount AS amount',
        "concat('Every ', recurring_donations.interval, ' ', recurring_donations.time_unit, '(s)') AS interval",
        '(SUM(paid_charges.amount) / 100.0)::money::text AS total_contributed',
        ...
end
result.map { |r| update_amount_with_currency(r, currency) }
```
update_amount_with_currency function:
```ruby
def self.update_amount_with_currency(query_row, currency)
    if query_row[1] != 'Amount'
      query_row[1] = print_currency(query_row[1], currency, true, true)
    end
    query_row
  end
```

2022-08-22 19:05 UTC, wwahammy requested changes
So I think you're going in the right direction but we're not quite there yet. I think it'd make sense to add a module whose sole method is `print_currency`. Then you can reference that method in ApplicationHelper, QueryDonations and QueryRecurringDonations

I think the most logical place to put this is in the `app/legacy_lib/format/currency.rb` file. From there you should be able to reference it in all three places.

2022-09-15 11:00 UTC, murilogds commented
Hi @wwahammy, we made the changes you asked in the code but we don't know how and where should we add the documentation for the print_currency method. Can you help us with that?

2022-09-21 15:50 UTC, wwahammy commented
Hi @murilogds, sorry about not getting back to you until now.

You should document the method using the YARD documentation standard. In particularly, the description, the parameters and what is returned. An example of doing so can be found at https://yardoc.org/features.html

2022-09-25 14:03 UTC, murilogds commented
> Hi @murilogds, sorry about not getting back to you until now.
> 
> You should document the method using the YARD documentation standard. In particularly, the description, the parameters and what is returned. An example of doing so can be found at https://yardoc.org/features.html

Thanks for the guide @wwahammy I updated the Pull Request with the documentation, can you review it?

2022-09-26 16:35 UTC, wwahammy requested changes
Very good work! There's a few minor tweaks needed but otherwise, it's almost ready to merge.

2022-09-26 16:35 UTC, wwahammy commented on app/legacy_lib/query_donations.rb
> +    currency = Nonprofit.find(nonprofit_id).currency_symbol
I think this would be better as follows:
```suggestion
    currency = Campaign.find(campaign_id).nonprofit.currency_symbol
```

2022-09-26 16:35 UTC, wwahammy commented on app/legacy_lib/query_donations.rb
> +    if query_row[1].to_s.downcase != 'amount'
Please add a comment before this line explaining that you're doing this to skip the header row. It makes sense to do it but I don't think it's obvious just from looking at it.

2022-09-26 16:35 UTC, wwahammy commented on app/legacy_lib/query_recurring_donations.rb
> +    if query_row[1] != 'Amount'
Same comment as above about providing a comment to explain this line.

2022-09-26 16:35 UTC, wwahammy commented on app/legacy_lib/format/currency.rb
> +      dollars = number_to_currency(dollars, unit: unit.to_s, precision: !use_precision && dollars.round == dollars ? 0 : 2)
Does this work with you use `ActiveSuppor::NumberHelper.number_to_currency` instead? If so, I think it'd make more sense to use than and not do the include of `ActiveSupport::NumberHelper`. We're only using that single method from `ActiveSupport::NumberHelper` and only using it in one place.

2022-09-26 16:35 UTC, wwahammy commented on app/legacy_lib/query_donations.rb
> +
Super minor tweak but could you remove this new line break?

2022-10-18 17:26 UTC, wwahammy commented
Hi @murilogds @Giuulob89, just checking in. Is this ready for review?

2022-11-05 12:20 UTC, murilogds commented
Sorry for the delay @wwahammy I forgot to ask your review

2022-11-05 18:13 UTC, wwahammy approved these changes
Looks good to me!

2022-11-05 18:14 UTC, merged

2022-11-05 18:14 UTC, wwahammy commented
Thanks for all the help  @murilogds @Giuulob89!